whatever:
	javac net/starmen/pkhack/*.java
	javac net/starmen/pkhack/eb/*.java
	javac net/starmen/pkhack/ct/*.java
	javac net/starmen/pkhack/som/*.java
	javac net/starmen/pkhack/wof/*.java
	jar cvfe JHack.jar net.starmen.pkhack.JHack net
	rm net/starmen/pkhack/wof/*.class
	rm net/starmen/pkhack/som/*.class
	rm net/starmen/pkhack/ct/*.class
	rm net/starmen/pkhack/eb/*.class
	rm net/starmen/pkhack/*.class

title:
	javac net/starmen/pkhack/*.java
	javac net/starmen/pkhack/eb/*.java
	javac net/starmen/pkhack/ct/*.java
	javac net/starmen/pkhack/som/*.java
	javac net/starmen/pkhack/wof/*.java
	jar cvfe JHack.jar net.starmen.pkhack.Main net
	rm net/starmen/pkhack/wof/*.class
	rm net/starmen/pkhack/som/*.class
	rm net/starmen/pkhack/ct/*.class
	rm net/starmen/pkhack/eb/*.class
	rm net/starmen/pkhack/*.class